nohup python3 main.py ../../rsc/experiment_configs/zeroshot/cola-zeroshot.json 0 > cola.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/mnli-zeroshot.json 1 > mnli.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/mr-zeroshot.json 2 > mr.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/mrpc-zeroshot.json 3 > mrpc.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/qnli-zeroshot.json 4 > qnli.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/qqp-zeroshot.json 5 > qqp.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/rte-zeroshot.json 6 > rte.zeroshot.log &
nohup python3 main.py ../../rsc/experiment_configs/zeroshot/snli-zeroshot.json 7 > snli.zeroshot.log &
#nohup python3 main.py ../../rsc/experiment_configs/zeroshot/sst2-zeroshot.json 3 > sst2.zeroshot.log &
#nohup python3 main.py ../../rsc/experiment_configs/zeroshot/subj-zeroshot.json 6 > subj.zeroshot.log &
